Repository segmentio/evergreen, pull requests merged in 2018-07, with the labels that each got.

#240 [v4] Fix button margin top
  src/buttons/src/Button.js
  src/buttons/stories/index.stories.js
  src/file-picker/test/snapshots/index.js.md
  src/file-picker/test/snapshots/index.js.snap
  src/ssr/test/snapshots/extractStyles.js.md
  src/ssr/test/snapshots/extractStyles.js.snap
Labels: Type: Bug

#241 [v4] Add focus to segmented control radios
  src/segmented-control/src/SegmentedControl.js
  src/segmented-control/src/SegmentedControlRadio.js
  src/theme/src/default-theme/component-specific/getSegmentedControlRadioClassName.js
  src/themer/src/createSegmentedControlRadioAppearance.js
Labels: Type: Improvement

#245 [v4] enable passing `defaultValue` for uncontrolled select inputs
  src/select/src/Select.js
Labels: Type: Improvement

#248 [v4] Fix icon placement in SidebarTab
  src/tabs/src/SidebarTab.js
Labels: Type: Bug

#257 [v4] Fix jitter in Positioner (Popover and Tooltip)
  src/popover/stories/index.stories.js
  src/positioner/src/Positioner.js
Labels: Type: Bug

#259 [v4] Improve Positioner calculations
  src/positioner/src/Positioner.js
  src/positioner/src/getPosition.js
Labels: Type: Bug

#264 Fix css SSR
  docs/src/pages/components/index.js
  docs/src/templates/component.js
Labels: Type: Bug

#266 Bug/on cancel
  src/corner-dialog/src/CornerDialog.js
  src/dialog/src/Dialog.js
Labels: Priority: High, Type: Bug

#269 [v4] Fix missing state in getButtonClassName
  src/theme/src/default-theme/component-specific/getButtonClassName.js
Labels: Type: Bug

#271 [v4] improve Table.VirtualBody
  src/table/src/TableVirtualBody.js
  src/table/stories/index.stories.js
Labels: Priority: High, Type: Improvement
