Repository segmentio/evergreen, pull requests merged in 2020-04, with the labels that each got.

#744 removed unused proptype
  src/text-input/src/TextInputField.js
Labels: Type: Documentation

#724 Migrates Spinner component to hooks
  src/spinner/src/Spinner.js
Labels: Type: Improvement

#727 Converts Pane component to hooks
  src/layers/src/Pane.js
Labels: Type: Improvement

#799 rm side effects in v5
  package.json
  src/backwards-compat-classname.js
  src/index.js
Labels: v5
